version: "3.8"

services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        command: "npm run dev"
        volumes:
            - ./api:/api
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=admin
            - DB_PASSWORD=admin
            - DB_NAME=auth
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=auth
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d auth"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres-data:
